---
title: "test_alt_across_k"
format:
  html:
    embed-resources: true
---

```{r}
library(tidyverse)
library(kableExtra)
library(foreach)
library(doParallel)
library(cluster)
registerDoParallel(cores = detectCores() - 1)
set.seed(599)

source(here::here("functions.R"))

getPointVecHelper <- function(i, mean_matrix) {
  # Given a point i and the mean matrix, should
  # return vector of all values in the mean matrix corresponding to obs i
  # after removing all NAs and then taking absolute value
  
  row <- mean_matrix[i, ]
  col <- mean_matrix[, i]
  
  # We don't care about the order, just the values themselves
  res_vec <- c(row, col)
  res_vec <- abs(res_vec[!is.na(res_vec)])
  return(res_vec)
  
}

point_contribution <- function(data, mean_matrix) {
  # Given the original data (the dataset inputted into the resample_matrices function),
  # and the mean_matrix, returns each observation's contribution to the cRab Score.
  # We don't necessarily require the second arg to be the mean matrix, for example
  # it could be resample matrix j.
  # This is returned as an (index, score) dataframe.
  
  # Get a list of lists containing index and index "cRab" score
  scores <- lapply(c(1:nrow(data)), function(i) {
    full_vec <- getPointVecHelper(i, mean_matrix)
    singlePointScore <- mean((1 - full_vec)^2)
    return(list(index = i, singlePointScore = singlePointScore))
  })
  final_df <- do.call(rbind.data.frame, scores)
  total_score <- mean(final_df$singlePointScore)
  
  final_df <- final_df |> 
    mutate(singlePointContribution = singlePointScore / total_score)
  
  return(final_df)
}

```

```{r}
crab_k_across <- function(data = data,
                          c_vec = c_vec,
                          formula = ~ .,
                          number_of_resamples = 80,
                          proportion_resample = 0.8,
                          starting_seed = 599,
                          algorithm = "kmeans") {
  # Calls the resampling function across the dataset, with the parameters
  # passed to the resampling function.
  
  # Returns a dataframe with k rows (one for each element in the c_vec cluster vector)
  # and a value for the cRab score after running the cRab algorithm on the dataset.
  
  result <- lapply(c(c_vec), function(k) {
    resample_matrices <- resample_function(data = data,
                                           formula = formula,
                                           k = k,
                                           number_of_resamples = number_of_resamples,
                                           proportion_resample = proportion_resample,
                                           starting_seed = starting_seed,
                                           algorithm = algorithm)
    m_matrix <- mean_matrix(resample_matrices)
    score <- squared_distance_from_one(m_matrix)
    print(k)
    print(image(m_matrix))
    e <- point_contribution(data, m_matrix)
    
    print(data |> 
      ggplot(aes(x = V1, y = V2,
             color = log(e$singlePointContribution))) +
        geom_jitter() +
        scale_color_distiller(type = "div",
                        palette = "Spectral") +
        theme_minimal()
      )
    return(list(k = k,
                cRab = score))
  })
  return(dplyr::bind_rows(result))
}

# https://cs.uef.fi/sipu/datasets/
test_data <- read.table(here::here("thesis/data/a1.txt")) |> 
  # slice_sample(prop = 0.33) |> 
  mutate(V1 = as.numeric(scale(V1)),
         V2 = as.numeric(scale(V2)))

test_data |> 
  ggplot(aes(x = V1, y = V2)) +
  geom_point()


res <- crab_k_across(test_data,
                     c_vec = c(15:25))

res |> 
  ggplot(aes(x = k, y = cRab)) +
  geom_line()

res

# resample <- resample_function(test_data, k = 20)
# 
# mean <- mean_matrix(resample)

# image(mean)
```

```{r}
data <- test_data
max_k <- 25
res <- lapply(c(1:max_k), function(i) {
  WCSS <- kmeans(data,
                 centers = i,
                 nstart = 10)$tot.withinss
  if (i == 1) {
    s <- data.frame(t(c(NA, NA, NA)))
  } else {
    s <- silhouette(kmeans(data, centers = i, nstart = 10)$cluster,
                  dist(data))
  }
  return(data.frame(k = as.vector(i),
                    WCSS = as.vector(WCSS),
                    Silhouette = mean(s[, 3])))
})

bind_rows(res) |> 
  ggplot(aes(x = k, y = WCSS)) +
  geom_point() +
  geom_line() +
  theme_minimal() +
  scale_x_continuous(breaks = 1:max_k)

bind_rows(res) |>  
  ggplot(aes(x = k, y = Silhouette)) +
  geom_point() + 
  geom_line() + 
  theme_minimal() + 
  scale_x_continuous(breaks = 1:max_k)
```

```{r}
# test_data <- read.table(here::here("thesis/data/s1.txt")) |> 
#   slice_sample(prop = 0.5) |>
#   mutate(V1 = as.numeric(scale(V1)),
#          V2 = as.numeric(scale(V2)))
# 
# test_data |> 
#   ggplot(aes(x = V1, y = V2)) +
#   geom_point()
# res <- crab_k_across(test_data,
#                      c_vec = c(2:20))
# res |>
#   ggplot(aes(x = k, y = cRab)) +
#   geom_line()
# 
# res |>
#   ggplot(aes(x = k, y = var)) +
#   geom_line()
# res
```

